blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('category/<int:pk>/', views.category, name='category'),
    path('tag/<int:pk>/', views.tag, name='tag'),
    path('search/', views.search, name='search'),
]

bs_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from bs_blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path(r'mdeditor/', include('mdeditor.urls')),
    path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
    path('more/', include(('more.urls', 'more'), namespace='more')),
    path('captcha/', include('captcha.urls'))
]

# 配置上传文件路径url 我猜
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 自定义django-markdown编辑器功能
# MDEDITOR_CONFIGS = {
# 'default':{
#     'width': '90%',  # 自定义编辑框宽度
#     'heigth': 500,   # 自定义编辑框高度
#     'toolbar': ["undo", "redo", "|",
#                 "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
#                 "h1", "h2", "h3", "h5", "h6", "|",
#                 "list-ul", "list-ol", "hr", "|",
#                 "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table", "datetime",
#                 "emoji", "html-entities", "pagebreak", "goto-line", "|",
#                 "help", "info",
#                 "||", "preview", "watch", "fullscreen"],  # 自定义编辑框工具栏
#     'upload_image_formats': ["jpg", "jpeg", "gif", "png", "bmp", "webp"],  # 图片上传格式类型
#     'image_folder': 'editor',  # 图片保存文件夹名称
#     'theme': 'default',  # 编辑框主题 ，dark / default
#     'preview_theme': 'default',  # 预览区域主题， dark / default
#     'editor_theme': 'default',  # edit区域主题，pastel-on-dark / default
#     'toolbar_autofixed': True,  # 工具栏是否吸顶
#     'search_replace': True,  # 是否开启查找替换
#     'emoji': True,  # 是否开启表情功能
#     'tex': True,  # 是否开启 tex 图表功能
#     'flow_chart': True,  # 是否开启流程图功能
#     'sequence': True,  # 是否开启序列图功能
#     'watch': True,  # 实时预览
#     'lineWrapping': False,  # 自动换行
#     'lineNumbers': False  # 行号
#     }
# }

more/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('login/', views.login_, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('findpwd/', views.findpwd, name='findpwd'),
    path('commit/', views.Commit, name='commit'),
    path('add/', views.post_add, name='add'),
    path('update/<int:pk>/', views.post_update, name='post_update'),
    path('delete/<int:pk>/', views.post_delete, name='post_delete'),
]

blog/models.py
import markdown
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
# 引入django中的timezone它可以自动帮我们处理时区的问题，只要你在settings.py中设置过时区
from django.utils import timezone
from django.utils.html import strip_tags
from mdeditor.fields import MDTextField


class Category(models.Model):
    name = models.CharField(verbose_name='分类', max_length=100)

    class Meta:
        verbose_name_plural = u'分类'
        verbose_name = verbose_name_plural

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(verbose_name='标签', max_length=100)

    class Meta:
        verbose_name_plural = u'标签'
        verbose_name = verbose_name_plural

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(verbose_name='标题', max_length=70)
    # body = models.TextField(verbose_name='正文', )
    body = MDTextField(verbose_name='内容')
    created_time = models.DateTimeField(verbose_name='创建时间', default=timezone.now)
    modified_time = models.DateTimeField(verbose_name='修改时间', )
    excerpt = models.CharField(verbose_name='摘要', max_length=200, blank=True)
    category = models.ForeignKey(verbose_name='分类', to='Category', on_delete=models.CASCADE)
    tag = models.ManyToManyField(verbose_name='标签', to='Tag', blank=True)
    author = models.ForeignKey(verbose_name='作者', to=User, on_delete=models.CASCADE)
    view = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        verbose_name_plural = '文章'
        verbose_name = verbose_name_plural


    # 写一个统计浏览次数的方法
    def increase_views(self):
        self.view += 1
        # 这里只指定更改views字段能提高效率
        self.save(update_fields=['views'])

    # 重写models.Model的save方法,让模型每次更改时都能自己获取当前时间
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        # 设置保存模型时自动保存修改时间
        self.modified_time = timezone.now()
        # 设置不手动输入摘要时，自动截取内容前部分字符作为摘要,也可使用过滤器中的truncatechars:55
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
        ])
        # strip_tags 为django html截取字符函数
        self.excerpt = strip_tags(md.convert(self.body))[:55]
        super().save()

    def __str__(self):
        return self.title

comments/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
import blog.models


class Comments(models.Model):
    name = models.CharField(verbose_name='名字', max_length=50)
    email = models.EmailField(verbose_name='邮箱')
    url = models.URLField(verbose_name='网址', blank=True)
    text = models.TextField(verbose_name='内容')
    created_time = models.DateTimeField(verbose_name='创建时间', default=timezone.now)
    post = models.ForeignKey(verbose_name='文章', to='blog.Post', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '评论'
        verbose_name = verbose_name_plural

    def __str__(self):
        return '{}:{}'.format(self.name, self.text[:20])

blog/views.py
import re
import markdown
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.text import slugify
from django.views.generic import ListView
from markdown.extensions.toc import TocExtension
from .models import Post, Category, Tag


class Index(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 5
    ordering = ['-created_time']


# def index(request):
#     if request.session.get('is_login', None):
#         print(333)
#         uid = request.session.get('uid')
#         # uid = int(uid)
#         post_list = Post.objects.filter(id=uid)
#         return render(request, 'blog/index.html', context={'post_list': post_list})
#     return redirect('more:login')


# 文章详情
def detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    # 每次请求了页面，让浏览次数加1
    post.increase_views()
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',  # 多种基础扩展
        'markdown.extensions.codehilite',  # 代码高亮
        # 'markdown.extensions.toc',  # 允许生成markdown目录
        TocExtension(slugify=slugify),  # 使用markdown中文锚点
    ])
    post.body = md.convert(post.body)
    post.toc = md.toc
    # 这里我们正则表达式去匹配生成的目录中包裹在ul标签中的内容，如果不为空，说明目录，就把ul
    # 标签中的值提取出来（目的是只要包含目录内容的最核心部分，多余的HTML标签结构丢掉）赋值给post.toc；否则，将
    # post的toc置为空字符串，然后我们就可以在模板中通过判断post.toc是否为空，来决定是否显示侧栏目录：
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    post.toc = m.group(1) if m is not None else ''
    return render(request, 'blog/detail.html', {'post': post})


# 完善归档功能，使点击归档能够得到相应的文章列表, 日期归档
def archive(request, year, month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month).order_by(
        '-created_time')
    return render(request, 'blog/index.html', {'post_list': post_list})
    # 注意这里created_time是Python的date对象，其有一个year和month属性，我们在页面侧边栏：使用自定义模板标签使用过这个属性。Python中调用属性的方式通常是created_time.year，但是由于这里作为方法的参数列表，所以django要求我们把点替换成了两个下划线，即created_time__year。


# 完善归档功能，使点击归档能够得到相应的文章列表, 分类归档
def category(request, pk):
    cate = get_object_or_404(Category, id=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'blog/index.html', {'post_list': post_list})


# 完善归档功能，使点击归档能够得到相应的文章列表, 标签归档
def tag(request, pk):
    t = get_object_or_404(Tag, id=pk)
    post_list = Post.objects.filter(tag=t).order_by('-created_time')
    return render(request, 'blog/index.html', {'post_list': post_list})


# 查找含有搜索关键词的文章
def search(request):
    q = request.GET.get('q')
    if not q:
        error_msg = "请输入搜索关键词"
        messages.add_message(request, messages.ERROR, error_msg, extra_msg='danger')
        return redirect('blog:index')

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {
        'post_list': post_list
    })

templates/blog/detail.html
{% extends 'base.html' %}
{% load comments_extras %}
{% block main %}
{#设置弹出确认框#}
<script>
function confirmAct()
{
    if(confirm('确定要执行此操作吗?'))
    {
        return true;
    }
    return false;
}
</script>


    {% if request.session.is_login %}
    <div class="comment-form">
    <div class="col-md-12">
    <a href="{% url 'more:post_update' post.pk %}"><button  class="comment-btn" >编辑</button></a>
    <a onclick="return confirmAct();" href="{% url 'more:post_delete' post.pk %}"><button  class="comment-btn" onclick="alertTips()">删除</button></a>

    </div>
    </div>
    {% endif %}
<article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#comment-area ">{{ post.comments_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.view }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix ">
            {{ post.body|safe }}
        </div>
    </article>
<section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>

        {% show_comments_form  post %}

        <div class="comment-list-panel">
            {% show_comments_list post %}
        </div>


    </section>
{% endblock main %}



{% block toc %}
  {% if post.toc %}
    <div class="widget widget-content">
      <h3 class="widget-title">文章目录</h3>
      <div class="toc">
        <ul>
          {{ post.toc|safe }}
        </ul>
      </div>
    </div>
  {% endif %}
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
        {% for post in post_list %}
                <article class="post post-{{ post.id }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="{% url 'blog:detail' post.id %}#comment-area ">{{ post.comments_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.view }} 阅读</a></span>
                        </div>
                    </header>
                <div class="entry-content clearfix">
                    <p>{{ post.excerpt }}</p>
                    <div class="read-more cl-effect-14">
                        <a href="{% url 'blog:detail' post.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                    </div>
                </div>
                </article>

            {% empty %}
                <div class="no-post">暂时还没有发布的文章！</div>
            {% endfor %}


                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
    {% if is_paginated %}
        <div class="pagination-simple">
        <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
        <!-- 显示当前页面信息 -->
        <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
        <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
        </div>
        {% endif %}

        {% endblock main %}

{#                <div class="pagination">#}
{#                    <ul>#}
{#                        <li><a href="">1</a></li>#}
{#                        <li><a href="">...</a></li>#}
{#                        <li><a href="">4</a></li>#}
{#                        <li><a href="">5</a></li>#}
{#                        <li class="current"><a href="">6</a></li>#}
{#                        <li><a href="">7</a></li>#}
{#                        <li><a href="">8</a></li>#}
{#                        <li><a href="">...</a></li>#}
{#                        <li><a href="">11</a></li>#}
{#                    </ul>#}
{#                </div>#}