blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('category/<int:pk>/', views.category, name='category'),
    path('tag/<int:pk>/', views.tag, name='tag'),
    path('search/', views.search, name='search'),
]

bs_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from bs_blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path(r'mdeditor/', include('mdeditor.urls')),
    path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
    path('more/', include(('more.urls', 'more'), namespace='more')),
    path('captcha/', include('captcha.urls'))
]

# 配置上传文件路径url 我猜
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 自定义django-markdown编辑器功能
# MDEDITOR_CONFIGS = {
# 'default':{
#     'width': '90%',  # 自定义编辑框宽度
#     'heigth': 500,   # 自定义编辑框高度
#     'toolbar': ["undo", "redo", "|",
#                 "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
#                 "h1", "h2", "h3", "h5", "h6", "|",
#                 "list-ul", "list-ol", "hr", "|",
#                 "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table", "datetime",
#                 "emoji", "html-entities", "pagebreak", "goto-line", "|",
#                 "help", "info",
#                 "||", "preview", "watch", "fullscreen"],  # 自定义编辑框工具栏
#     'upload_image_formats': ["jpg", "jpeg", "gif", "png", "bmp", "webp"],  # 图片上传格式类型
#     'image_folder': 'editor',  # 图片保存文件夹名称
#     'theme': 'default',  # 编辑框主题 ，dark / default
#     'preview_theme': 'default',  # 预览区域主题， dark / default
#     'editor_theme': 'default',  # edit区域主题，pastel-on-dark / default
#     'toolbar_autofixed': True,  # 工具栏是否吸顶
#     'search_replace': True,  # 是否开启查找替换
#     'emoji': True,  # 是否开启表情功能
#     'tex': True,  # 是否开启 tex 图表功能
#     'flow_chart': True,  # 是否开启流程图功能
#     'sequence': True,  # 是否开启序列图功能
#     'watch': True,  # 实时预览
#     'lineWrapping': False,  # 自动换行
#     'lineNumbers': False  # 行号
#     }
# }

more/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('login/', views.login_, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('findpwd/', views.findpwd, name='findpwd'),
    path('commit/', views.Commit, name='commit'),
    path('add/', views.post_add, name='add'),
    path('update/<int:pk>/', views.post_update, name='post_update'),
    path('delete/<int:pk>/', views.post_delete, name='post_delete'),
]

templates/base.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}/">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %} "></script>
    <!-- 代码高亮 -->

</head>

<body>
<script src="{% static 'blog/js/script.js' %}"></script>
{% block nav %}
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'more:login' %}" data-hover="登录">登录</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->

                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
{% endblock nav %}
{#    发送的消息被缓存在cookie中，然后我们在模板中获取显示即可。显示消息比较好的地方是在导航条的下面，我们在模板#}
{#    base.html的导航条代码下增加如下代码：#}
{#      且目前项目cookies为django默认设置，为全局上下文变量，所以不需要传递messages变量#}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}

                {% endblock main %}
            </main>
        {% block rightside %}
            <aside class="col-md-4">
                {% block toc %}

                {% endblock toc %}


              {% show_recent_posts %}
              {% show_archives %}
              {% show_categories %}
              {% show_tags %}

{#  <div class="rss">#}
{#     <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>#}
{#  </div>#}
            </aside>
{% endblock rightside %}
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2022 <a href="#"
                                                        target="_blank" title="联系我">联系我</a>
                    - 欢迎到<a href="#" title="网页模板" target="_blank">xxx@gmail.com</a>交流
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

templates/commit_code.html
{% extends 'base.html' %}
{% block nav %}
{% endblock nav %}
{% block main %}
		<div class="content-body" style="margin-top: 50px">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">找回密码</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="{% url 'more:commit' %}" method="post" class="contact-form">
                                    {% csrf_token %}
									<div class="row">
										<div class="col-md-6 col-md-offset-3">

                                                {{ commit }}


{#                                            <input type="text" name="name" placeholder="用户名" required="">#}
{#                                            <label for="id_username">用户名:</label>#}
{#                                            <input type="text" name="username" class="form-control" placeholder="Username" autofocus="" maxlength="128" required="" id="id_username">#}

                                            <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>修改密码</span></button>


										</div>

									</div>	<!-- row -->

								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright"><a href="{% url 'more:register' %}" style="color: red">没有账号？去注册</a></p>
					</div>
				</div>
			</div>
		</footer>
{% endblock main %}
		<!-- Mobile Menu -->
{% block rightside %}
{% endblock rightside %}

		<script src="js/script.js"></script>
{#验证码刷新#}
<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
<script>
     //点击刷新验证码
<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
<script>
     //点击刷新验证码
    $(function () {
        $('.captcha').css({
            'cursor': 'pointer'
        });
        // ajax刷新
        $('.captcha').click(function () {
            console.log('click');
            $.get("{% url 'captcha-refresh' %}",
                function (result) {
                    $('.captcha').attr('src', result['image_url']);
                    $('#id_captcha_1').val(result['key'])
                });
        });
    })
</script>
</script>
	</body>
</html>

templates/findpwd.html
{% extends 'base.html' %}
{% block nav %}
{% endblock nav %}
{% block main %}
		<div class="content-body" style="margin-top: 50px">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">找回密码</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="{% url 'more:findpwd' %}" method="post" class="contact-form">
                                    {% csrf_token %}
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
                                            {{ form }}


{#                                            <input type="text" name="name" placeholder="用户名" required="">#}
{#                                            <label for="id_username">用户名:</label>#}
{#                                            <input type="text" name="username" class="form-control" placeholder="Username" autofocus="" maxlength="128" required="" id="id_username">#}

                                            <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>发送邮件</span></button>


										</div>

									</div>	<!-- row -->

								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright"><a href="{% url 'more:register' %}" style="color: red">没有账号？去注册</a></p>
					</div>
				</div>
			</div>
		</footer>
{% endblock main %}
		<!-- Mobile Menu -->
{% block rightside %}
{% endblock rightside %}

		<script src="js/script.js"></script>
{#验证码刷新#}
<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
<script>
     //点击刷新验证码
<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
<script>
     //点击刷新验证码
    $(function () {
        $('.captcha').css({
            'cursor': 'pointer'
        });
        // ajax刷新
        $('.captcha').click(function () {
            console.log('click');
            $.get("{% url 'captcha-refresh' %}",
                function (result) {
                    $('.captcha').attr('src', result['image_url']);
                    $('#id_captcha_1').val(result['key'])
                });
        });
    })
</script>
</script>
	</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% block nav %}
{% endblock nav %}
{% block main %}
		<div class="content-body" style="margin-top: 50px">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">登录</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="{% url 'more:login' %}" method="post" class="contact-form">
                                    {% csrf_token %}
									<div class="row">
										<div class="col-md-6 col-md-offset-3">

                                            {{ form.username }}

                                            {{ form.password }}

                                            {{ form.captcha }}

{#                                            <input type="text" name="name" placeholder="用户名" required="">#}
{#                                            <label for="id_username">用户名:</label>#}
{#                                            <input type="text" name="username" class="form-control" placeholder="Username" autofocus="" maxlength="128" required="" id="id_username">#}

                                            <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>登录</span></button>


										</div>

									</div>	<!-- row -->

								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright"><a href="{% url 'more:register' %}" style="color: red">没有账号？去注册</a></p>
                        <p class="copyright"><a href="{% url 'more:findpwd' %}" style="color: red">忘记密码？</a></p>
					</div>
				</div>
			</div>
		</footer>
{% endblock main %}
		<!-- Mobile Menu -->
{% block rightside %}
{% endblock rightside %}

		<script src="js/script.js"></script>
{#验证码刷新#}
<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
<script>
     //点击刷新验证码
<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
<script>
     //点击刷新验证码
    $(function () {
        $('.captcha').css({
            'cursor': 'pointer'
        });
        // ajax刷新
        $('.captcha').click(function () {
            console.log('click');
            $.get("{% url 'captcha-refresh' %}",
                function (result) {
                    $('.captcha').attr('src', result['image_url']);
                    $('#id_captcha_1').val(result['key'])
                });
        });
    })
</script>
</script>
	</body>
</html>

templates/new.html
{% extends 'base.html' %}
{% load static %}

<script src="{% static 'edit.css' %}"></script>
{% block nav %}
{% endblock nav %}
{% block main %}

		<div class="content-body" style="margin-top: 50px">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">新增文章</h1>
						<article class="post">
							<div class="entry-content clearfix" >
								<form action="{% url 'more:add' %}" method="post" class="contact-form">
                                    {% csrf_token %}
									<div class="row" >
										<div class="col-md-6 col-md-offset-3" >
                                            {{ form.as_p}}



                                            {{ form.media }}
                                            <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>新增文章</span></button>
{#                                            <input type="text" name="title" placeholder="标题" required>#}
{#                                            <input type="text" name="tag1" placeholder="标签1" required>#}
{#                                            <input type="text" name="tag2" placeholder="标签2" required>#}
{#                                            <input type="text" name="category" placeholder="Subject" required>#}
{#                                            <textarea name="body" rows="7" placeholder="Your Message"#}
{#                                                      required></textarea>#}

{#                                            <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>登录</span></button>#}


										</div>

									</div>	<!-- row -->

								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">

					</div>
				</div>
			</div>
		</footer>
{% endblock main %}
		<!-- Mobile Menu -->
{% block rightside %}
{% endblock rightside %}

		<script src="js/script.js"></script>
{#验证码刷新#}
<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
<script>
     //点击刷新验证码
<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
<script>
     //点击刷新验证码
    $(function () {
        $('.captcha').css({
            'cursor': 'pointer'
        });
        // ajax刷新
        $('.captcha').click(function () {
            console.log('click');
            $.get("{% url 'captcha-refresh' %}",
                function (result) {
                    $('.captcha').attr('src', result['image_url']);
                    $('#id_captcha_1').val(result['key'])
                });
        });
    })
</script>
</script>
	</body>
</html>


    <input type="text" name="name" placeholder="Name" required>
    <input type="email" name="email" placeholder="Email" required>
    <input type="text" name="subject" placeholder="Subject" required>
    <textarea name="message" rows="7" placeholder="Your Message" required></textarea>
    <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>

templates/register.html
{% extends 'base.html' %}
{% block nav %}
{% endblock nav %}
{% block main %}
		<div class="content-body" style="margin-top: 50px">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">注册</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
                                    {% csrf_token %}
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											{{ form }}
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>提交</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>

{% endblock main %}
		<!-- Mobile Menu -->
{% block rightside %}
{% endblock rightside %}

		<script src="js/script.js"></script>
		
	</body>
</html>